// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeekMap.Data;

#nullable disable

namespace WeekMap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817195145_ProbaMigracija")]
    partial class ProbaMigracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WeekMap.Models.ActivityCategory", b =>
                {
                    b.Property<long>("ActivityCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityCategoryID"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ActivityCategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("ActivityCategories", (string)null);
                });

            modelBuilder.Entity("WeekMap.Models.ActivityTemplate", b =>
                {
                    b.Property<long>("ActivityTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityTemplateID"), 1L, 1);

                    b.Property<long?>("ActivityCategoryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ActivityTemplateID");

                    b.HasIndex("ActivityCategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("ActivityTemplates", (string)null);
                });

            modelBuilder.Entity("WeekMap.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WeekMap.Models.UserDefaultWeekMapSettings", b =>
                {
                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("DayEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DayStartTime")
                        .HasColumnType("time");

                    b.Property<bool>("ShowDescriptionInPreview")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPlaceInPreview")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.ToTable("UserDefaultWeekMapSettings", (string)null);
                });

            modelBuilder.Entity("WeekMap.Models.UserSettings", b =>
                {
                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("WeekMap.Models.WeekMap", b =>
                {
                    b.Property<long>("WeekMapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WeekMapID"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("DayEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DayStartTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ShowDescriptionInPreview")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPlaceInPreview")
                        .HasColumnType("bit");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("WeekMapID");

                    b.HasIndex("UserID");

                    b.ToTable("PlannedWeekMaps", (string)null);
                });

            modelBuilder.Entity("WeekMap.Models.WeekMapActivity", b =>
                {
                    b.Property<long>("WeekMapActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WeekMapActivityID"), 1L, 1);

                    b.Property<DateTime?>("ActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ActivityTemplateID")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("OnFriday")
                        .HasColumnType("bit");

                    b.Property<bool>("OnMonday")
                        .HasColumnType("bit");

                    b.Property<bool>("OnSaturday")
                        .HasColumnType("bit");

                    b.Property<bool>("OnSunday")
                        .HasColumnType("bit");

                    b.Property<bool>("OnThursday")
                        .HasColumnType("bit");

                    b.Property<bool>("OnTuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("OnWednesday")
                        .HasColumnType("bit");

                    b.Property<bool>("RepeatEveryWeek")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<long>("WeekMapID")
                        .HasColumnType("bigint");

                    b.HasKey("WeekMapActivityID");

                    b.HasIndex("ActivityTemplateID");

                    b.HasIndex("WeekMapID");

                    b.ToTable("WeekMapActivities", (string)null);
                });

            modelBuilder.Entity("WeekMap.Models.ActivityCategory", b =>
                {
                    b.HasOne("WeekMap.Models.User", "User")
                        .WithMany("ActivityCategories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeekMap.Models.ActivityTemplate", b =>
                {
                    b.HasOne("WeekMap.Models.ActivityCategory", "ActivityCategory")
                        .WithMany()
                        .HasForeignKey("ActivityCategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WeekMap.Models.User", "User")
                        .WithMany("ActivityTemplates")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeekMap.Models.UserDefaultWeekMapSettings", b =>
                {
                    b.HasOne("WeekMap.Models.User", "User")
                        .WithOne("UserDefaultWeekMapSettings")
                        .HasForeignKey("WeekMap.Models.UserDefaultWeekMapSettings", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeekMap.Models.UserSettings", b =>
                {
                    b.HasOne("WeekMap.Models.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("WeekMap.Models.UserSettings", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeekMap.Models.WeekMap", b =>
                {
                    b.HasOne("WeekMap.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeekMap.Models.WeekMapActivity", b =>
                {
                    b.HasOne("WeekMap.Models.ActivityTemplate", "ActivityTemplate")
                        .WithMany()
                        .HasForeignKey("ActivityTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeekMap.Models.WeekMap", "WeekMap")
                        .WithMany()
                        .HasForeignKey("WeekMapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityTemplate");

                    b.Navigation("WeekMap");
                });

            modelBuilder.Entity("WeekMap.Models.User", b =>
                {
                    b.Navigation("ActivityCategories");

                    b.Navigation("ActivityTemplates");

                    b.Navigation("UserDefaultWeekMapSettings")
                        .IsRequired();

                    b.Navigation("UserSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
